name: spine_flutter_example
description: Demonstrates how to use the spine_flutter plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <4.0.0'
  flutter: ">=3.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  spine_flutter:
    path: ../
  cupertino_icons: ^1.0.6
  flame: ^1.10.1
  raw_image_provider: ^0.2.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/